# Generated by Django 6.0.6 on 2026-06-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menuview'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
